import { useNavigate } from "react-router-dom";
import "../App.css";

export default function Landing() {
  const navigate = useNavigate();

  return <main className="cashready-landing">
    <section className="hero-section"><div className="hero-main"><div className="hero-copy"><p className="eyebrow">SMART CASH, STRONGER BANKING</p><h1>ATM Cash Management</h1><p className="hero-description">Real-time ATM Monitoring, Predictive Cash Forecasting, Smart<br className="desktop-break" /> Route Optimization and Enterprise Banking Analytics.</p><div className="hero-actions"><button className="primary-action" type="button" onClick={() => navigate("/home")}>Explore Platform <span>→</span></button><button className="secondary-action" type="button" onClick={() => navigate("/contact")}>Request Demo</button></div></div><div className="metric-stack" aria-label="Platform metrics"><div className="metric-card"><strong>98.7%</strong><span>Cash Availability</span></div><div className="metric-card"><strong>2,450</strong><span>ATMs Monitored</span></div></div></div><div className="hero-overview-grid"><article><span className="overview-number">01</span><h3><span className="overview-icon" aria-hidden="true">⌖</span>Find the right ATM</h3><p>Search nearby terminals by distance, location, and current cash availability.</p></article><article><span className="overview-number">02</span><h3><span className="overview-icon" aria-hidden="true">◌</span>Plan before demand peaks</h3><p>Turn live network signals and withdrawal patterns into confident replenishment plans.</p></article><article><span className="overview-number">03</span><h3><span className="overview-icon" aria-hidden="true">▣</span>Operate with confidence</h3><p>Give teams a clear view of terminal health, priority alerts, and operational activity.</p></article></div></section>
    <section className="service-strip"><span>◈ 24/7 Operations Support</span><span>⌖ Live ATM availability</span><span>▣ Trusted banking intelligence</span></section>
  </main>;
}